[[headers]]
  # Налаштування для всіх запитів
  for = "/*"
      [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/admin/*"
      [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/checkout/*"
      [headers.values]
    Cache-Control = "public, max-age=31536000"
